# project deployment app
name: CD Deploy to github pages

on:
 push:
  branches: [ master ]

jobs:
 deploy-app-gh-pages: 
  runs-on: ubuntu-latest
  strategy:
   matrix:
    node-version: [ "12" ]
  name: deploy app
  steps:
   - uses: actions/checkout@v2
   - uses: actions/setup-node@v1
     with:
      node-version: ${{ matrix.node.node-version }}
   - name: install gatsby
     run: npm install -g gatsby-cli
   - name: install packages
     run: npm install
   - name: registry user
     run: |
        git config --global user.email jhonyvegacuya24@gmail.com
        git config --global user.name jhony-24
   - name: build project
     run: npm run deploy
     env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      GATSBY_TOKEN_API_WORD: ${{ secrets.GATSBY_TOKEN_API_WORD }}
      GATSBY_FIREBASE_API_KEY: ${{ secrets.GATSBY_FIREBASE_API_KEY }}
      GATSBY_FIREBASE_APP_ID: ${{ secrets.GATSBY_FIREBASE_APP_ID }}
      GATSBY_FIREBASE_STORAGE_BUCKET: ${{ secrets.GATSBY_FIREBASE_STORAGE_BUCKET }}
